### ISSUE TITLE
[Question] Templates

### ISSUE THREAD

**Issue by noraj** [pavanw3b/sh00t#11]
What is the template engine or language for templates? Is there methods to use Sh0ts data? Maybe a generic one can be added?

**Comment by pavanw3b** [comment]
Hey Alexandre, I believed I answered your question. Let me know if you are still looking for help.

**Comment by noraj** [comment]
> Is there methods to use Sh0ts data?
I thought I was a template for report where we could add Sh0ts data like `{{ sh0ths.title }}`, etc.
