### ISSUE TITLE
Missing methodology

### ISSUE THREAD

**Issue by jangelesg** [pavanw3b/sh00t#21]
During a Fresh installation, the templates does not show in the methodology section

**Comment by pavanw3b** [comment]
Hey @jangelesg 
Thanks for reporting. Let me check and will address it this week.

**Comment by noraj** [comment]
Confirmed, I did a fresh new install in a virtual env and neither WAHH or OWASP methodologies are loaded.

**Comment by pavanw3b** [comment]
Hey guys, did you follow the instructions accurately?
A new just installation won't load the methodologies, you will need to run `python reset.py`

Anyway, with the latest virtualenv instruction, the `setup.sh` or `setup.bat` will run the reset and make the methodologies available.

**Comment by pavanw3b** [comment]
I just tried again. It loaded the methodologies.
Make sure to run `python reset.py` for older versions, or with the latest, the .`/setup.sh` or `setup.bat` will load the methodologies. Remember to type "Yes" when it says "Are you sure you wanna do this?", the default answer is No.
May be we can change the script to not wait for `Yes` in a fresh installation. Not all want to load the methodologies by default IMO, will think about it.

**Comment by noraj** [comment]
@pavanw3b Ok I chose "No". Maybe what "Reset" do is unclear at install time?

**Comment by pavanw3b** [comment]
Yep, I absolutely agree it wasn't clear. I'm going to change the script that will pass "Yes" internally at the time of installation.

**Comment by pavanw3b** [comment]
Docker ready! It also automatically loads the methodologies. Changed the setup script to bypass asking the question. The alternative installation instruction will execute `python3 setup.py first_timer` which will reset and load the methodologies. So this should be fully closed now.
