### ISSUE TITLE
Default Login creds do not work: sh00t:sh00t

### ISSUE THREAD

**Issue by Hax0rG1rl** [pavanw3b/sh00t#28]
Hi, 

Got this deployed by using docker.  I am facing an odd situation, the default login creds do not work, sh00t: sh00t. 

Is there any way to check/reset the default password manually? 

Thanks.

**Comment by pavanw3b** [comment]
Hey @Hax0rG1rl,
That's strange. I'll check in detail later, I'll keep this issue open but for now, you can open shell of docker and change the user password.

`docker exec -it sh00t bash`
`source env/bin/activate`
`python manage.py changepassword sh00t`.
if you get an error saying sh00t user doesn't exists,
try `python manage.py createsuperuser`

All the above instructions are just top of mind, if something not right, you can get answers on Docker or Django by checking on the search engine. Let me know if you face any difficulties.

I'll check again why the default set up is not working.

**Comment by Hax0rG1rl** [comment]
Hi @pavanw3b, 

Check this as an FYI. The user does not exist. I followed your additional steps and it worked.

Also, **docker exec -it sh00t bash** does not work. 

```
docker exec -it sh00t bash
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
``'

I had to get in following one of the workarounds from here: 

https://stackoverflow.com/questions/48001082/oci-runtime-exec-failed-exec-failed-executable-file-not-found-in-path 

![image](https://user-images.githubusercontent.com/3704868/63719779-dd52ed00-c8a1-11e9-8d2d-71cd677af387.png)

Thanks!

**Comment by jieOneStr** [comment]
the exec command will work if you replace bash with sh

**Comment by pavanw3b** [comment]
> the exec command will work if you replace bash with sh

Oh yes. Thanks. Have updated my above comments for new visitors here.

**Comment by pavanw3b** [comment]
The fix is ready in dev track. Testing it. Will merge to master soon.

**Comment by pavanw3b** [comment]
The fix was tested and image has been pushed to Docker. Thank you all for reporting this issue and supporting with work-around.
