### ISSUE TITLE
import results from ZAP

### ISSUE THREAD

**Issue by jangelesg** [pavanw3b/sh00t#3]
Hello Bro,

I'd like to discus the option to enhance the tools creating a new feature that allows the pentester to import results from ZAP PROXY and image for the evidence that is really helpful when you have to explain how to recreate the issue that was found during the testing time frame.

**Comment by pavanw3b** [comment]
Hey @jangelesg,
Sure, that sounds great! I'm currently coping up with my jet lag. We can connect in a couple of days. I'll reach out to you asap.

**Comment by pavanw3b** [comment]
Hey @jangelesg 
How to contact you? Can you share your Skype or Twitter id?

**Comment by jangelesg** [comment]
twitter - ex0dday
skype-ekx0day@gmail.com

**Comment by jangelesg** [comment]
any news bro ..

**Comment by pavanw3b** [comment]
Hey @jangelesg,
I have already sent you a message on Skype and an email too. Let's catch up there.

**Comment by pavanw3b** [comment]
Thanks @jangelesg, I've sent you email.

**Comment by jangelesg** [comment]
hey bro .. is this something that i can help out to code

**Comment by pavanw3b** [comment]
Hey @jangelesg,
That would be great if you can help!

**Comment by jangelesg** [comment]
hey sorry for the delay but id like to retake this how can add this functionality
