### ISSUE TITLE
Ability to mark mark flags as done on /app/flags/all/

### ISSUE THREAD

**Issue by lam0r** [pavanw3b/sh00t#7]
Hi there,

it would be great to be able to mark flags as done on the overview page as some items just do not apply to the current tests and to mark them one does have to open them, mark them as done and apply the changes afterwards.

Thanks in advance.

**Comment by pavanw3b** [comment]
Hey @lam0r,
I agree with this completely. Will add this feature in the next release. It's good one, appreciate it. Thank you!

**Comment by pavanw3b** [comment]
Hey @lam0r ,
Just to keep you updated about the progress, today I pushed some updates that was required for the requirement you requested, I'm targeting to complete the functionality of marking multiple flags as done by next weekend. I'll let you know once it's ready.

**Comment by lam0r** [comment]
Thank You for the Update :-)

**Comment by pavanw3b** [comment]
Hey @lam0r,
This is done!

Now users should be able to mark multiple flags as done. We have a separate page for open flags too.
All the remaining pages get multiple delete option and with pagination support.

git pull the latest, update your sh00t set up. Don't forget to tell me how do you find this change.
