### ISSUE TITLE
[Question] virtual environment

### ISSUE THREAD

**Issue by noraj** [pavanw3b/sh00t#9]
Anaconda is a python distribution that embed tons of data scientif packages, and that allow the creation of a virtual environment.
Miniconda is just conda without all packages.
So if conda is only used to create a virtual environment, why not using pure python + [virtualenv](https://github.com/pypa/virtualenv) instead of an eavy conda distribution?
It will be far lighter to do exactly the same thing.

**Comment by noraj** [comment]
Exemple for archlinux

```
# pacman -S python python-virtualenv
$ git clone https://github.com/pavanw3b/sh00t && cd sh00t
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
...
```

**Comment by pavanw3b** [comment]
Hey @noraj,
Thanks for checking this.

Sure, I agree. Env can be anything that has Py3 and Django installed. I chose miniconda over virtualenv, pyenv etc because it worked smooth in multiple platforms. I had some challenge with Virtualenv on Windows, wanted a simplest set up for Sh00t users.
However, I'll check again to consider Virtualenv on your suggestion. Thanks again!

**Comment by noraj** [comment]
@pavanw3b Yep, maybe you can put in the README the steps I provided as an alternative.

**Comment by pavanw3b** [comment]
Sure.

**Comment by pavanw3b** [comment]
Trying to add instructions to use virtualenv. Pushed some changes here: https://github.com/pavanw3b/sh00t/tree/venv_setup
Will test thoroughly again and merge to master.

**Comment by noraj** [comment]
@pavanw3b Any news on merging that branch ?

**Comment by pavanw3b** [comment]
Hey @noraj,
Was busy at work. Some testing pending with the venv setup instructions. Targeting to finish this along with a couple of other items this week.

**Comment by noraj** [comment]
When you'll have do it, I'll test sh00t again. And I'll package it for BlachArch.

**Comment by pavanw3b** [comment]
Hey guys,
Virtualenv and simpler set up is now ready!

@noraj Thank you. It's ready for your review now.

**Comment by pavanw3b** [comment]
Will work on Docker this week. For now virtualenv is ready!

**Comment by noraj** [comment]
Installation is better now !
